# Generated by Django 4.2.14 on 2025-01-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/media'),
        ),
        migrations.DeleteModel(
            name='PostMedia',
        ),
    ]
