# Generated by Django 4.2.14 on 2025-01-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_system', '0002_post_img_delete_postmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=2564, null=True),
        ),
    ]
