# Generated by Django 4.2.14 on 2025-01-01 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_system', '0003_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
